# Generated by Django 4.1.6 on 2023-03-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='ceiling_height',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='housing_type',
            field=models.CharField(choices=[('Вторичный рынок', 'Вторичный рынок'), ('Новостройка', 'Новостройка')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='layout',
            field=models.CharField(choices=[('Смежная', 'Смежная'), ('Раздельная', 'Раздельная'), ('Смежно-раздельная', 'Смежно-раздельная'), ('Студия', 'Студия'), ('Пентхаус', 'Пентхаус'), ('Многоуровневая', 'Многоуровневая'), ('Малосемейка', 'Малосемейка')], max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='rent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='building_type',
            field=models.CharField(choices=[('Панельный дом', 'Панельный дом'), ('Кирпичный дом', 'Кирпичный дом'), ('Монолитный дом', 'Монолитный дом'), ('Блочный дом', 'Блочный дом'), ('Деревянный дом', 'Деревянный дом')], max_length=20, null=True),
        ),
    ]
