# Generated by Django 4.1.6 on 2023-03-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_basemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
